proyecto_final/app/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SelectField, RadioField
from wtforms.validators import DataRequired, Length


class CreateCategoryForm(FlaskForm):
    category_name = StringField('Nombre', validators=[DataRequired()])


class CreateProductForm(FlaskForm):
    name = StringField('Nombre', validators=[DataRequired(), Length(max=50, message="Nombre demasiado largo")])
    image = StringField('Imagen URL', validators=[DataRequired()])
    price = IntegerField('Precio', validators=[DataRequired()])
    description = StringField('Descripción', validators=[DataRequired(), Length(max=500)])
    refundable = SelectField('Reembolso', choices=[("True", 'Es reembolsable'), ("", 'No reembolsable')], coerce=bool)
    category_id = IntegerField('Id de Categoria', validators=[DataRequired()])


class UpdateStockForm(FlaskForm):
    product_id = IntegerField('Id del producto', validators=[DataRequired()])
    quantity = IntegerField('Cantidad a añadir', validators=[DataRequired()])

proyecto_final/app/admins/views.py
from http import HTTPStatus

from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_required
from werkzeug.security import generate_password_hash

from app.admins.forms import CreateAdminForm
from app.admins.models import get_admin_by_email, create_admin_user

adminBp = Blueprint("adminBp", __name__, url_prefix="/admins")


@adminBp.route('/admin-panel/', methods=['GET'])
@login_required
def admin_panel():
    """
        Render the admin panel
        ---
        tags:
            - admins
        description: Shows a panel with all the options available to the admin
        responses:
            200:
              description: Rendered correctly
    """
    return render_template("admin-panel.html"), HTTPStatus.OK


@adminBp.route("/add-product", methods=["GET", "POST"])
@login_required
def create_product():
    """
        Render the new product form
        ---
        tags:
            - admins
        description: Show a form to add a new product to the database
        responses:
            200:
              description: Rendered correctly
    """
    return render_template("add-product-form.html"), HTTPStatus.OK


@adminBp.route("/add-category", methods=["GET", "POST"])
@login_required
def create_category():
    """
        Render the new category form
        ---
        tags:
            - admins
        description: Show a form to add a new category to the database
        responses:
            200:
              description: Rendered correctly
    """
    return render_template("add-category-form.html"), HTTPStatus.OK


@adminBp.route("/update-stock", methods=["GET", "POST"])
@login_required
def update_stock():
    """
        Render the new stock product form
        ---
        tags:
            - admins
        description: Show a form to add a new stock product to the database
        responses:
            200:
              description: Rendered correctly
    """
    return render_template("update-stock.html"), HTTPStatus.OK


@adminBp.route("/add-admin", methods=["GET", "POST"])
@login_required
def add_admin():
    form_admin = CreateAdminForm()
    if request.method == "POST" and form_admin.validate():
        admin_name = form_admin.admin_name.data
        email = form_admin.email.data
        password = form_admin.admin_password.data
        hash_password = generate_password_hash(password)

        if get_admin_by_email(email=email):
            flash("El correo ya esta siendo utilizado")
        else:
            if create_admin_user(admin_name=admin_name, admin_password=hash_password, email=email):
                flash("Admin creado correctamente")
            else:
                flash("Fallo al crear admin")

    return render_template("add-admin-form.html", form=form_admin), HTTPStatus.OK

proyecto_final/app/orders/views.py
from http import HTTPStatus

from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user, login_required

from app.products.models import get_product_by_id
from app.payment_methods.models import get_customer_payment_methods_by_customer_id, get_ref_payment_methods, get_customer_payment_method_by_id
from app.orders.models import (
    get_order_in_process_by_customer_id,
    create_order_item,
    get_order_item_by_product_id,
    get_order_items_by_order_id,
    delete_order_item_by_id,
    create_invoice,
    create_payment,
    change_status_order_by_customer_id
)

from app.orders.models import create_order

order = Blueprint("order", __name__, url_prefix="/order")


@order.route("/add-order-item", methods=['POST'])
@login_required
def add_order_item():
    """
        Add item order
        ---
        tags:
            - orders
        description: Add an item to the order in process of payment
        parameters:
            - in: header
              name: product_id
              description: The identification of the product that will be linked to the item of the order.
              type: integer
            - in: header
              name: quantity
              description: Quantity of the product to be purchased
              type: integer
            - in: header
              name: price
              description: Unit price of the product to be added to the order
              type: integer
        responses:
            200:
              description: The order item has been created
            400:
              description: The product had already been added to the cart
            500:
              description: Internal problem

    """
    product_id = request.form["product_id"]
    if get_order_item_by_product_id(product_id=product_id):
        cart_response = "Exist"
        response = HTTPStatus.BAD_REQUEST
    else:
        product_quantity = int(request.form["quantity"])
        user_id = current_user.id
        order_in = get_order_in_process_by_customer_id(customer_id=user_id)

        if order_in:
            order_id = order_in['id']
            product_price = int(request.form["price"])
            order_item_status_code = "OSI2"
            if create_order_item(product_id=product_id, order_id=order_id,
                                 order_item_status_code=order_item_status_code,
                                 order_item_quantity=product_quantity,
                                 order_item_price=(product_price * product_quantity)):
                cart_response = "Added"
                response = HTTPStatus.OK
            else:
                cart_response = "Fatal_Error"
                response = HTTPStatus.INTERNAL_SERVER_ERROR

        else:
            order_in = create_order(customer_id=user_id)

            order_id = order_in['id']
            product_price = int(request.form["price"])
            order_item_status_code = "OSI2"

            if create_order_item(product_id=product_id, order_id=order_id, order_item_status_code=order_item_status_code,
                                 order_item_quantity=product_quantity, order_item_price=(product_price*product_quantity)):
                cart_response = "Added"
                response = HTTPStatus.OK
            else:
                cart_response = "Fatal_Error"
                response = HTTPStatus.INTERNAL_SERVER_ERROR

    return redirect(url_for('store.show_product_view', product_id=product_id, cart_response=cart_response)), response


@order.route("/order-view", methods=["GET", "POST"])
@login_required
def show_order():
    if request.method == "POST":
        order_item_id = request.form["order_item_id"]
        if delete_order_item_by_id(order_item_id=order_item_id):
            return "Error"
    customer_id = current_user.id
    order_in = get_order_in_process_by_customer_id(customer_id=customer_id)
    if order_in:
        order_items = get_order_items_by_order_id(order_in["id"])
        if order_items:
            order_items_iva_prices = []
            order_subtotal_prices = []
            product_names = []
            total_price = 0
            for order_item in order_items:
                iva_price = (order_item["order_item_price"]*0.19)
                order_items_iva_prices.append(iva_price)
                subtotal_price = (iva_price+order_item["order_item_price"])
                total_price = total_price+subtotal_price
                order_subtotal_prices.append(subtotal_price)
                product = get_product_by_id(product_id=order_item["product_id"])
                product_name = product["name"]
                product_names.append(product_name)

            order_information = {"order_items": order_items, "order_items_iva_prices": order_items_iva_prices,
                                 "order_subtotal_prices": order_subtotal_prices, "product_names": product_names,
                                 "total_price": total_price}
            customer_payment_methods = get_customer_payment_methods_by_customer_id(customer_id=customer_id)
            ref_payment_methods = get_ref_payment_methods()


        else:
            order_information = {}
            customer_payment_methods = None
            ref_payment_methods = None
    else:
        order_information = {}
        ref_payment_methods = None
        customer_payment_methods = None

    return render_template("shopping-cart.html", order_information=order_information, pay=customer_payment_methods, refer=ref_payment_methods)


@order.route("/pay-order", methods=["POST"])
@login_required
def pay_order():
    """
       An order is paid
       ---
       tags:
           - orders
       description: An order payment is made and the invoice and payment are generated.
       parameters:
           - in: header
             name: payment-method-selection
             description: The card that the user selected for payment
             type: string
           - in: header
             name: payment_amount
             description: The total amount of the order
             type: integer
       responses:
           200:
             description: The order was paid and generated
           500:
             description: Could not update order
           500:
             description: The invoice could not be generated
           500:
             description: The payment could not be generated
       """
    credit_card_id = request.form["payment-method-selection"]
    payment_method = get_customer_payment_method_by_id(credit_card_id)
    payment_amount = request.form["payment_amount"]
    customer_id = current_user.id
    order_in = get_order_in_process_by_customer_id(customer_id=customer_id)
    invoice_status_code = "IS1"
    if payment_method["payment_method_code"] == "01A":
        invoice_details = "Factura pagada por Crédito"
    elif payment_method["payment_method_code"] == "02A":
        invoice_details = "Factura pagada por Débito"

    invoice = create_invoice(order_id=order_in["id"], invoice_status_code=invoice_status_code, invoice_details=invoice_details)
    if invoice:
        invoice_number = invoice.number
        payment = create_payment(invoice_number=invoice_number, payment_amount=payment_amount)
        if payment:
            if change_status_order_by_customer_id(customer_id=customer_id):
                message = "Error al actualizar la orden"
                response = HTTPStatus.INTERNAL_SERVER_ERROR
            else:
                message = "Se ha efectuado el pago exitosamente"
                response = HTTPStatus.OK
        else:
            message = "Ha ocurrido un error con el pago"
            response = HTTPStatus.INTERNAL_SERVER_ERROR
    else:
        message = "Ha ocurrido un error con la factura"
        response = HTTPStatus.INTERNAL_SERVER_ERROR

    flash(message)
    return render_template("payment_result.html")

proyecto_final/app/products/views.py
from http import HTTPStatus
from flask import Blueprint, Response, request, render_template, flash
from flask_login import login_required

from app.products.forms import CreateCategoryForm, CreateProductForm, UpdateStockForm

from app.products.models import (
    create_stock_by_product,
    update_product_stock,
    get_product_by_id,
    get_all_categories,
    create_new_category,
    get_all_products,
    create_new_product,
    get_products_by_category,
    get_category_by_id
)


store = Blueprint("store", __name__, url_prefix="/store")

EMPTY_SHELVE_TEXT = "Empty shelve!"
PRODUCTS_TITLE = "<h1> Products </h1>"
DUMMY_TEXT = "Dummy method to show how Response works"
RESPONSE_BODY = {"message": "", "data": [], "errors": [], "metadata": []}


# Pagina de inicio de la tienda
@store.route('/home/')
def home_page():
    """
    Redirect home page
    ---
    tags:
        - store
    description: Redirects the user from the root path to the homepage
    responses:
        302:
          description: The URL has been changed
    """
    return render_template("home.html")


# Vista para crear categorias
@store.route("/add-category/", methods=["GET", "POST"])
def create_category():
    """
    :return:
    """
    form_category = CreateCategoryForm()
    message = ""

    if request.method == 'POST' and form_category.validate():
        message = create_new_category(category_name=form_category.category_name.data)

    return render_template('add-category-form.html', form=form_category, message=message)


# Vista para crear productos
@store.route("/add-product/", methods=["GET", "POST"])
@login_required
def create_product():

    form_product = CreateProductForm()
    categories = get_all_categories()
    message = ""
    if request.method == 'POST' and form_product.validate():
        message = create_new_product(name=form_product.name.data, image=form_product.image.data, price=form_product.price.data,
                                     description=form_product.description.data, refundable=form_product.refundable.data,
                                     category_id=form_product.category_id.data)

    flash(form_product.errors)

    return render_template('add-product-form.html', form=form_product, message=message, categories=categories)


@store.route("/update-stock", methods=['GET', 'POST'])
@login_required
def update_stock():
    """
        Render stock form and update stock data in db
        ---
        tags:
            - products
        get:
            summary: Render the stock form
            description: Render the form to update or add the stock of a product
            responses:
                200:
                  description: Successful rendering
    """
    form_stock = UpdateStockForm()
    message = ""
    if request.method == "POST" and form_stock.validate():
        product_id = form_stock.product_id.data
        quantity = form_stock.quantity.data
        product = get_product_by_id(product_id=product_id)
        if product:
            stock_result = update_product_stock(product_id=product_id, new_quantity=quantity)
            if stock_result:
                message = stock_result
            else:
                message = create_stock_by_product(product_id=form_stock.product_id.data, quantity=form_stock.quantity.data)
        else:
            message = "El producto referido no existe"
            response = HTTPStatus.NOT_FOUND

    print(message)
    return render_template('update-stock.html', message=message, form=form_stock), response


# Vista para un catalogo de productos segun su categoria
@store.route("/category/<category_id>/", methods=['GET'])
def show_products_by_category(category_id):
    """
    Displays a catalog of products
    ---
    tags:
        - products
    description: Displays a catalog of products according to the indicated category
    parameters:
        - in: path
          name: category_id
          description: The id of the category corresponding to the product group
          type: integer
    responses:
        200:
          description: Render the template with the products of the category
        404:
          description: There is no products to show
    """
    products = get_products_by_category(category_id=category_id)
    category = get_category_by_id(category_id=category_id)
    if products:
        response = HTTPStatus.NOT_FOUND
    else:
        response = HTTPStatus.OK
    return render_template("products_catalog.html", products=products, category=category), response


@store.route("/product/view/<product_id>/<string:cart_response>/")
def show_product_view(product_id, cart_response):
    """
        Displays product full view
        ---
        tags:
            - products
        description: Shows a more detailed view of the product, with its characteristics.
        parameters:
            - in: path
              name: product_id
              description: The id of the product
              type: integer
            - in: path
              name: cart_response
              description: The identifier of the response to "buy"
              type: string
        responses:
            200:
              description: Render the template with the full view product.
    """
    if cart_response == "Added":
        message = "Añadido al carrito satisfactoriamente"
    elif cart_response == "Exist":
        message = "Ya has añadido este producto, si quieres añadir mas ve al carrito"
    elif cart_response == "Error":
        message = "Fatal_Error"
    else:
        message = ""
    product = get_product_by_id(product_id)
    return render_template("product-view.html", product=product, message=message)

proyecto_final/app/templates/add-admin-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Category</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/addAdminStyle.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script src="{{ url_for('static', filename='js/PcStoreCode.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
</head>
<body>
    <div class="pageContainer">
        <div class="button-back-container">
            <button class="ui button" onclick="goToPanel();">
                <i class="ui left arrow icon"></i>
            </button>
        </div>
        <div class="ui middle aligned center aligned grid">
             <div class="column">
                 <h1 class="ui top attached block header">
                    Agregar cuenta admin
                 </h1>
                 <div class="ui bottom attached segment">
                     <form action="{{ url_for('adminBp.add_admin') }}" class="ui form" method="post">
                         {{ form.csrf_token }}
                         <div class="field">
                             <h4 class="ui header">
                                {{ form.admin_name.label }}
                            </h4>
                                {{ form.admin_name }}
                         </div>
                         <div>
                             <div class="field">
                             <h4 class="ui header">
                                {{ form.email.label }}
                            </h4>
                                {{ form.email }}
                         </div>
                         <div>
                             <div class="field">
                             <h4 class="ui header">
                                {{ form.admin_password.label }}
                            </h4>
                                {{ form.admin_password }}
                         </div>
                         </div>
                         <div class="field">
                             <button type="submit" class="ui button">Agregar</button>
                         </div>
                     </form>
                     {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="ui yellow message">
                            {{ messages[0] }}
                        </div>
                        {% endif %}
                    {% endwith %}
                 </div>
             </div>
        </div>
    </div>
    <script>
        function goToPanel(){
            location.href="{{ url_for('adminBp.admin_panel') }}"
        }
    </script>
</body>
</html>

proyecto_final/app/templates/add-category-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Category</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/addCategoryStyle.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script src="{{ url_for('static', filename='js/PcStoreCode.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
</head>
<body>
    <div class="pageContainer">
        <div class="button-back-container">
            <button class="ui button" onclick="goToPanel();">
                <i class="ui left arrow icon"></i>
            </button>
        </div>
        <div class="ui middle aligned center aligned grid">
             <div class="column">
                 <h1 class="ui top attached block header">
                    Agregar nueva categoria
                 </h1>
                 <div class="ui bottom attached segment">
                     <form action="{{ url_for('store.create_category') }}" class="ui form" method="post">
                         {{ form.csrf_token }}
                         <div class="field">
                             <h4 class="ui header">
                                {{ form.category_name.label }}
                            </h4>
                                {{ form.category_name }}
                         </div>
                         <div class="field">
                             <button type="submit" class="ui button">Agregar</button>
                         </div>
                     </form>
                     {% if message %}
                        <div class="ui success message">
                            <h3 class="ui header">{{ message }}</h3>
                        </div>
                     {% endif %}
                 </div>
             </div>
        </div>
    </div>
    <script>
        function goToPanel(){
            location.href="{{ url_for('adminBp.admin_panel') }}"
        }
    </script>
</body>
</html>

proyecto_final/app/templates/admin-panel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>4DM1NS</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/adminPanelStyle.css') }}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
</head>
<body>
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <h1 class="ui top attached block header">
                ¡Bienvenido administrador {{ current_user.admin_name }}!
            </h1>
            <div class="ui bottom attached segment">
                <div class="ui selection massive animated list">
                    <div class="item" id="add-product-sect" onclick="goToProducts();">
                        <h2><i class="small circular cube icon"></i>Agregar productos</h2>
                    </div>
                    <div class="item" onclick="goToCategorys();">
                        <h2><i class="small circular cubes icon"></i> Agregar Categorias</h2>
                    </div>
                    <div class="item" onclick="goToStock();">
                        <h2><i class="small circular truck icon"></i> Actualizar el Stock</h2>
                    </div>
                    <div class="item" onclick="goToPayMethods();">
                        <h2><i class="small circular credit card icon"></i> Agregar metodos de pago </h2>
                    </div>
                    <div class="item" onclick="goToAddAdmins()">
                        <h2><i class="small circular user plus icon"></i> Agregar administradores </h2>
                    </div>
                    <div class="item" onclick="Logout();">
                        <h2><i class="small circular power off icon"></i> Cerrar Sesion </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function goToProducts(){
            location.href = "{{ url_for('store.create_product') }}"
        }
        function goToCategorys(){
            location.href = "{{ url_for('store.create_category') }}"
        }
        function goToStock(){
            location.href = "{{ url_for('store.update_stock') }}"
        }
        function goToPayMethods(){
            location.href = "{{ url_for('paymentMethods.create_payment_method') }}"
        }
        function goToAddAdmins(){
            location.href = "{{ url_for('adminBp.add_admin') }}"
        }
        function Logout(){
            location.href = "{{ url_for('userBp.logout') }}"
        }
    </script>
</body>
</html>

proyecto_final/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% block tittle %}{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='images/logo.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/baseStyle.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <script src="{{ url_for('static', filename='js/PcStoreCode.js') }}"></script>
    {% endblock %}
</head>
<body>
    <div class="ui sidebar">
        <div class="ui left vertical inverted menu sidebar" id="sidebar-menu">
            <div class="item">
                <div class="ui blue header">PC Componentes</div>
                <div class="menu">
                    <a class="item" id="sidebar-item" href="/store/category/1/">
                      Procesadores
                    </a>
                    <a class="item" id="sidebar-item">
                      Memorias RAM
                    </a>
                    <a class="item" id="sidebar-item">
                      Discos Duros
                    </a>
                </div>
            </div>
            <div class="item">
                <div class="ui blue header">Computadores</div>
                <div class="menu">
                    <a class="item" id="sidebar-item">Portatiles</a>
                    <a class="item" id="sidebar-item">De Escritorio</a>
                </div>
            </div>
            <div class="item">
                <div class="ui blue header">Perifericos</div>
                <div class="menu">
                    <a href="" class="item" id="sidebar-item">Teclados</a>
                    <a href="" class="item" id="sidebar-item">Ratones</a>
                    <a href="" class="item" id="sidebar-item">Altavoces</a>
                    <a href="" class="item" id="sidebar-item">Monitores</a>
                </div>
            </div>
        </div>
    </div>
    <div class="pusher">
        <div id="header">
            <div class="ui secondary menu" id="menu">
                <div class="item" id="products-sidebar-activator">
                    <div class="ui inverted basic button">
                        <i class="sidebar icon"></i> Productos
                    </div>
                </div>
                <div class="center-container">
                    <div class="logo-container"></div>
                    <a href="{{ url_for('store.home_page')}}" class="logo-link">
                        <img class="logo" src="{{ url_for('static', filename='images/logo.png') }}" alt="CompuTech">
                        <h2 id="logTittle">CompuTech Store</h2 class="ui item">
                    </a>
                </div>
                <div class="right menu">
                    <div class="item">
                        <button class="ui button" onclick="goToShoppingCar()">
                            <i class="shop icon"></i>
                        </button>
                    </div>
                    <div class="item">
                        <button class="ui button" id="acces-btn">
                            <i class="icon user"></i>
                            {% if current_user.is_authenticated %}
                                {{ current_user.login_name }}
                            {% else %}
                               Acceder
                            {% endif %}
                        </button>
                        <div class="ui inverted popup">
                            <div class="ui inverted middle aligned link list">
                                {% if current_user.is_authenticated %}
                                    <a href="{{ url_for('userBp.account')}}" class="item">Cuenta</a>
                                    <a href="{{ url_for('userBp.logout')}}" class="item">Cerrar Sesion</a>
                                {% else %}
                                    <a href="{{ url_for('userBp.login')}}" class="item" >Iniciar Sesion</a>
                                    <a href="{{ url_for('userBp.signup')}}" class="item">Registrarse</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui modal">
                <div class="ui attached centered aligned segment">
                    <h1 class="ui centered aligned red header">Función no disponible</h1>
                    <p class="infoModal">Debes iniciar sesion para poder realizar una compra</p>
                </div>
                <div class="ui bottom attached right aligned segment">
                    <div class="ui buttons">
                      <button class="ui button" id="boton-Cancelar">Cancelar</button>
                      <div class="or" data-text="o"></div>
                      <form action="{{ url_for('userBp.login')}}">
                          <button class="ui positive button">Iniciar Sesion</button>
                      </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
        {% block footer %}
        <div class="ui vertical footer segment" id="footer-segment">
            <h1 class="ui header">Contacto y derechos</h1>
        </div>
        {% endblock %}
    </div>
    <script>
    {% block script %}
        $('#products-sidebar-activator').click(function () {
            $('#sidebar-menu').sidebar('toggle');
        })
        $('#acces-btn')
          .popup({
            popup : $('.popup'),
            on    : 'click'
          })
        ;
        $('.modal')
          .modal('attach events', '.animated.button', 'show')
          .modal('attach events', '#boton-Cancelar', 'hide')
        ;

        function goToShoppingCar(){
            location.href = "{{ url_for('order.show_order') }}"
        }
    {% endblock %}
    </script>
</body>
</html>